name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  self-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    - name: unit tests
      run: make test

    - name: Cache files
      uses: actions/cache@v3
      with:
        path: ./
        key: source-${{ github.sha }}
  
  lead-check-self:
    runs-on: ubuntu-latest
    needs: [self-test]
    steps:
    - name: Restore cached built files
      uses: actions/cache@v3
      with:
        path: ./
        key: source-${{ github.sha }}

    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1

    - name: Run valgrind leak check
      run: make valgrind
