name: Quality Assurance

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-test-self:
    runs-on: ubuntu-latest
    container: xanonymous/gtest-cpp-essential-env:latest

    steps:
    - uses: actions/checkout@v3

    - name: unit tests
      run: make test

    - name: Cache files
      uses: actions/cache@v3
      with:
        path: ./
        key: source-${{ github.sha }}
  
  leak-check-self:
    runs-on: ubuntu-latest
    container: xanonymous/gtest-cpp-essential-env:latest

    needs: [unit-test-self]
    steps:
    - name: Restore cached built files
      uses: actions/cache@v3
      with:
        path: ./
        key: source-${{ github.sha }}

    - name: Run valgrind leak check
      run: make valgrind && make valgrind_graphics
