name: Unit Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  self-test:
    runs-on: ubuntu-latest
    container: xanonymous/gtest-cpp-essential-env:latest

    steps:
    - uses: actions/checkout@v3

    - name: unit tests
      run: make test
